[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pkgwrap-lokesh"
version = "0.1.2"
description = "One command. Every package manager. Universal CLI wrapper for apt, pkg, pacman, dnf, apk, brew, zypper, xbps, nix, eopkg & FreeBSD pkg."
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "pkgwrap contributors"}
]
dependencies = []

[project.scripts]
pkgwrap = "pkgwrap.cli:main"
pkw = "pkgwrap.cli:main"
